apiVersion: v1
kind: Service
metadata:
  labels:
    app: stubby4node-service
  name: stubby4node-service
spec:
  type: ClusterIP
  ports:
    - name: default-port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: stubby4node-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: stubby4node-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stubby4node-pod
  template:
    metadata:
      labels:  
        app: stubby4node-pod
    spec:
      volumes:
        - name: volume-stubby4node
          configMap:
            name: config-stubby4node
      containers:
      - name: stubby4node
        image: tpsumeta/stubby4node:amd64
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
          - name: YAML_CONFIG
            value: "main.yaml"
          - name: PORT
            value: "8080"
          - name: ADMIN_PORT
            value: "8889"
          - name: TLS_PORT
            value: "7443"
          - name: WITH_DEBUG
            value: "--debug"
          - name: WITH_WATCH
            value: "--watch"
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 8889
          name: tls-port
        - containerPort: 7443
          name: admin-port
        volumeMounts:
          - name: volume-stubby4node
            mountPath: /home
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
